feat: add trustadvisor scrape support
flanksource/config-db pull request #12
Opened 2021-12-20 11:45 UTC by Kaitou786

The resulting isntance.json file:

```yaml
{
  "LastModified": "0001-01-01T00:00:00Z",
  "Type": "EC2Instance",
  "Id": "i-03b932aa5d836d5bb",
  "Config": {
    "Compliance": {
      "approved-amis-by-id": {
        "Id": "approved-amis-by-id",
        "Annotation": "",
        "ComplianceType": "NON_COMPLIANT",
        "ConfigRuleInvokedTime": "2021-11-03T08:29:24.689Z",
        "ResultRecordedTime": "2021-11-03T08:29:24.966Z"
      }
    },
    "ami_launch_index": 0,
    "architecture": "x86_64",
    "block_device_mappings": [
      {
        "DeviceName": "/dev/xvda",
        "Ebs": {
          "AttachTime": "2021-11-03T08:26:06Z",
          "DeleteOnTermination": true,
          "Status": "attached",
          "VolumeId": "vol-06ffd4df17efe6962"
        }
      }
    ],
    "ebs_optimized": false,
    "ena_support": true,
    "hypervisor": "xen",
    "image_id": "ami-041db4a969fe3eb68",
    "instance_id": "i-03b932aa5d836d5bb",
    "instance_type": "t2.micro",
    "key_name": "tarun",
    "launch_time": "2021-11-03T08:26:05Z",
    "network_interfaces": [
      {
        "AttachTime": "2021-11-03T08:26:05Z",
        "AttachmentId": "eni-attach-09e338c421acfa69c",
        "DeleteOnTermination": true,
        "DeviceIndex": 0,
        "NetworkCardIndex": 0,
        "AttachmentStatus": "attached",
        "Description": "",
        "Groups": [
          "sg-0c3976c2247c98d0f"
        ],
        "Ipv4Prefixes": null,
        "Ipv6Addresses": null,
        "Ipv6Prefixes": null,
        "MacAddress": "02:33:a0:17:93:52",
        "NetworkInterfaceId": "eni-0f85cce39e76c45cd",
        "OwnerId": "",
        "PrivateDnsName": "ip-172-31-18-189.ap-south-1.compute.internal",
        "PrivateIpAddress": "172.31.18.189",
        "PrivateIpAddresses": [
          "172.31.18.189"
        ],
        "SourceDestCheck": true,
        "Status": "in-use"
      }
    ],
    "platform_details": "Linux/UNIX",
    "private_dns_name": "ip-172-31-18-189.ap-south-1.compute.internal",
    "private_ip_address": "172.31.18.189",
    "public_dns_name": "ec2-13-235-16-127.ap-south-1.compute.amazonaws.com",
    "public_ip_address": "13.235.16.127",
    "root_device_name": "/dev/xvda",
    "root_device_type": "ebs",
    "security_groups": {
      "sg-0c3976c2247c98d0f": "launch-wizard-1"
    },
    "source_dest_check": true,
    "state": "running",
    "subnet_id": "subnet-cf33c3a7",
    "usage_operation": "RunInstances",
    "usage_operation_update_time": "2021-11-03T08:26:05Z",
    "virtualization_type": "hvm",
    "vpc_id": "vpc-1424cc7c",
    "trusted_advisor_checks": [
      {
        "check_id": "Qch7DwouX1",
        "check_name": "Low Utilization Amazon EC2 Instances",
        "check_category": "cost_optimizing",
        "check_status": "warning",
        "metadata": {
          "14-Day Average CPU Utilization": "0.1%",
          "14-Day Average Network I/O": "0.01MB",
          "Day 1": "0.1%  0.00MB",
          "Day 10": "0.1%  0.00MB",
          "Day 11": "0.1%  0.01MB",
          "Day 12": "0.2%  0.01MB",
          "Day 13": "0.1%  0.05MB",
          "Day 14": "0.1%  0.05MB",
          "Day 2": "0.1%  0.00MB",
          "Day 3": "0.1%  0.00MB",
          "Day 4": "0.1%  0.00MB",
          "Day 5": "0.1%  0.00MB",
          "Day 6": "0.1%  0.00MB",
          "Day 7": "0.1%  0.00MB",
          "Day 8": "0.1%  0.05MB",
          "Day 9": "0.1%  0.00MB",
          "Estimated Monthly Savings": "$8.93",
          "Number of Days Low Utilization": "14 days"
        }
      },
      {
        "check_id": "HCP4007jGY",
        "check_name": "Security Groups - Specific Ports Unrestricted",
        "check_category": "security",
        "check_status": "error",
        "metadata": {
          "Ports": "22",
          "Protocol": "tcp",
          "Security Group ID": "sg-0c3976c2247c98d0f (vpc-1424cc7c)",
          "Security Group Name": "launch-wizard-1",
          "Status": "Yellow"
        }
      },
      {
        "check_id": "1iG5NDGVre",
        "check_name": "Security Groups - Unrestricted Access",
        "check_category": "security",
        "check_status": "error",
        "metadata": {
          "IP Range": "0.0.0.0/0",
          "Port": "22",
          "Protocol": "tcp",
          "Security Group ID": "sg-0c3976c2247c98d0f (vpc-1424cc7c)",
          "Security Group Name": "launch-wizard-1",
          "Status": "Red"
        }
      },
      {
        "check_id": "H7IgTzjTYb",
        "check_name": "Amazon EBS Snapshots",
        "check_category": "fault_tolerance",
        "check_status": "error",
        "metadata": {
          "Reason": "No snapshot",
          "Snapshot Age": "",
          "Snapshot ID": "",
          "Snapshot Name": "",
          "Status": "Red",
          "volume_attachment": "/dev/xvda"
        }
      }
    ]
  }
}
```

2021-12-20 11:54 UTC, moshloop commented
Can we move `
          "Estimated Monthly Savings": "$8.93",` outside of metatdata and make it numeric ?

2021-12-20 14:13 UTC, Kaitou786 commented
> Can we move ` "Estimated Monthly Savings": "$8.93",` outside of metatdata and make it numeric ?

Updated the json file in the PR comment above with this change

2021-12-21 16:02 UTC, moshloop requested changes

2021-12-21 16:02 UTC, moshloop commented on scrapers/aws/aws.go
> +func (t *TrustedAdvisorCheckResult) TrustedAdvisorCheckFromCheckResult(instanceId string, securityGroups map[string]string) *TrustedAdvisorCheck {
I would pass the EC2Instance through here directly

2021-12-23 11:37 UTC, merged