store Kubernetes events as changes.
flanksource/config-db pull request #164
Opened 2023-03-03 12:34 UTC by adityathebe

2023-03-04 19:45 UTC, moshloop commented on scrapers/kubernetes/events.go
> +		Details:          involvedObject,
The involved object isn't really relevant - it is more the full object, minus the involved object

2023-03-06 07:42 UTC, adityathebe commented on scrapers/kubernetes/events.go
> +	return fmt.Sprintf("kubernetes/%s/%s", host, component)
@moshloop is this alright? When I tested this some event objects had `null` host but the component's always there. Example:
```

kubernetes/<unknown-host>/default-scheduler
kubernetes/kind-control-plane/kubelet
```

2023-03-06 09:45 UTC, moshloop commented on scrapers/kubernetes/events.go
> +	return fmt.Sprintf("kubernetes/%s/%s", host, component)
I think maybe convert the map to key=val e.g `kubernetes/component=kubelet,host=kind-control-plane`

2023-03-06 16:33 UTC, yashmehrotra requested changes

2023-03-06 16:33 UTC, yashmehrotra commented on api/v1/kubernetes.go
> +type Event struct {
Use `KubernetesEvent` since its in the v1 package

2023-03-06 16:33 UTC, yashmehrotra commented on scrapers/kubernetes/events.go
> +			return "error"
shouldn't this be warn ?

2023-03-06 16:33 UTC, yashmehrotra commented on scrapers/kubernetes/events.go
> +		ExternalType:     ExternalTypePrefix + involvedObject["kind"].(string),
Should we type assert these and return err if it fails ?

2023-03-06 16:54 UTC, adityathebe commented on scrapers/kubernetes/events.go
> +		ExternalType:     ExternalTypePrefix + involvedObject["kind"].(string),
I believe `kind` and `uid` fields in `involvedObject` are always going to be a string https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectreference-v1-core.

I'll make changes so the program doesn't panic if they are nil.

2023-03-06 16:55 UTC, adityathebe commented on api/v1/kubernetes.go
> +type Event struct {
Made the change @yashmehrotra

2023-03-07 19:35 UTC, moshloop commented on scrapers/kubernetes/events.go
> +	return fmt.Sprintf("kubernetes/component=%s,host=%s", component, host)
We shouldn't assume component or host  or put in unknown host or componenet - we need to convert the source map into key=value generically, sorted by key,

2023-03-08 04:35 UTC, adityathebe commented on scrapers/kubernetes/events.go
> +	return fmt.Sprintf("kubernetes/component=%s,host=%s", component, host)
@moshloop I wasn't assuming that the source contains component & host only. I checked this reference - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#eventsource-v1-core to make sure of that.

2023-03-08 04:50 UTC, adityathebe commented on scrapers/kubernetes/events.go
> +	return fmt.Sprintf("kubernetes/component=%s,host=%s", component, host)
I made the changes so it's generic now.

2023-03-08 06:53 UTC, merged