feat: allow serviceAccount annotation configuration
flanksource/config-db pull request #226
Opened 2023-05-18 09:40 UTC by BrendanGalloway

- allows override to point to existing SA
- allows annotation injection when creating S
- cleaned up some nindent vs indent discrepencies

2023-05-18 09:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/flanksource/config-db?pullRequest=226) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/flanksource/config-db?pullRequest=226) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/flanksource/config-db?pullRequest=226) it.</sub>

2023-05-22 06:04 UTC, moshloop requested changes

2023-05-22 06:04 UTC, moshloop commented on chart/templates/_helpers.tpl
> +    {{ default (include "kube-prometheus-stack.operator.fullname" .) .Values.prometheusOperator.serviceAccount.name }}
I think this is a copy and paste error

2023-06-12 17:06 UTC, moshloop commented on chart/templates/_helpers.tpl
> +    {{ default (include "kube-prometheus-stack.operator.fullname" .) .Values.prometheusOperator.serviceAccount.name }}
@BrendanGalloway ^

2023-06-27 13:46 UTC, yashmehrotra approved these changes

2023-06-27 13:47 UTC, yashmehrotra commented
@moshloop Lets merge this ?

2023-06-27 13:55 UTC, merged