feat: upstream sync
flanksource/config-db pull request #300
Opened 2023-09-26 12:46 UTC by adityathebe

Merge after: https://github.com/flanksource/config-db/pull/299

2023-09-26 15:32 UTC, adityathebe commented on jobs/jobs.go
> +	ReconcileConfigsToUpstreamSchedule     = "@every 3h"
@moshloop let me know what these schedules should be.

2023-09-27 05:53 UTC, adityathebe commented on jobs/sync_upstream.go
> +	}
@moshloop Since we're using id instead of time to push data, wouldn't this mean that updates to already pushed records are not pushed anymore?

2023-09-27 06:34 UTC, adityathebe commented
## Pulling scrape configs 

a. Pull everything that was updated since X timestamp
- X could be empty on startup so agent fetches all scrape configs
- or it could be a delta of 5 minutes.

## Push config

### A.  Primary means of pushing to upstream

  a. use event_queue to push real time changes to upstream, **OR**
  b. On a schedule X, fetch all the results that were updated in the last (X + delta) interval. _(Although config_analysis doesn't have updated_at table so we might need to add it.)_

### B. Reconcile

Every 8 hours, push all results that were updated in the last 48 hours.

2023-09-27 06:59 UTC, moshloop commented on jobs/sync_upstream.go
> +	jobHistory := models.NewJobHistory("PushScraperConfigResultsToUpstream", "Config", "")
```suggestion
	jobHistory := models.NewJobHistory("PushUpstream", "Config", "")
```

2023-09-29 06:33 UTC, moshloop commented on jobs/jobs.go
> +	PullConfigScrapersFromUpstreamSchedule = "@every 30s"
```suggestion
	PullConfigScrapersFromUpstreamSchedule = "@every 5m"
```

2023-09-29 06:34 UTC, moshloop commented on cmd/root.go
> +	flags.StringVar(&api.UpstreamConfig.Host, "upstream-host", os.Getenv("UPSTREAM_HOST"), "central mission control instance to sync scrape configs & their results")
I think we need to add chart values as well

2023-09-29 07:11 UTC, moshloop commented
> ## Pulling scrape configs
> a. Pull everything that was updated since X timestamp
> 
> * X could be empty on startup so agent fetches all scrape configs
> * or it could be a delta of 5 minutes.
> 
> ## Push config
> ### A. Primary means of pushing to upstream
> a. use event_queue to push real time changes to upstream, **OR** b. On a schedule X, fetch all the results that were updated in the last (X + delta) interval. _(Although config_analysis doesn't have updated_at table so we might need to add it.)_
> 
> ### B. Reconcile
> Every 8 hours, push all results that were updated in the last 48 hours.
> 
> @moshloop wdyt?


Pulling scrape configs every 5 minutes or so is fine

For push I think the event_queue mechanism as the primary is fine + normal reconciliation. 

We will probably need to included updated_at in the hash,  and then in get upstream details return both ids and updated_at on hash mismatch, and only push the difference

2023-10-02 08:27 UTC, BrendanGalloway requested changes

2023-10-02 08:27 UTC, BrendanGalloway commented on chart/values.yaml
> +  agentName:
should this have a default?

2023-10-02 08:27 UTC, BrendanGalloway commented on chart/templates/deployment.yaml
> +              name: {{ .Values.upstream.secretKeyRef.name }}
```suggestion
            - secretRef:
                name: {{ .Values.upstream.secretKeyRef.name }}
```

2023-10-02 08:27 UTC, BrendanGalloway commented on chart/values.yaml
> +  secretKeyRef:
Maybe indicate which keys this secret is expected to contain

2023-10-02 08:30 UTC, BrendanGalloway commented on chart/templates/deployment.yaml
> +          envFrom:
must this secret _always_ be supplied?  if not, either wrapped this stanza with an if statement, or set the envFrom entry as optional

2023-10-02 09:13 UTC, adityathebe commented on chart/values.yaml
> +  secretKeyRef:
I suppose this done simply via a comment?

2023-10-02 12:00 UTC, BrendanGalloway approved these changes

2023-10-02 12:00 UTC, BrendanGalloway commented on chart/values.yaml
> +  secretKeyRef:
yes

2023-10-03 07:15 UTC, moshloop commented on chart/values.yaml
> +  enabled: true
```suggestion
  enabled: false
```

2023-10-05 06:46 UTC, merged